### ISSUE TITLE
Donation details page (without DonationItem)

### ISSUE THREAD

**Issue by ML-Chen** [GTBitsOfGood/umi-feeds-app#34]
The donation details page will display information about a single donation. It has the donation id passed to it as a prop. (To test the page, it might be helpful to set the donation id prop to some donation id in the database by default.) At the start of the component rendering, it should make a request to the backend to get the donation info—this would be an Axios GET request to /api/donations/:donation_id. Actually it looks like this endpoint doesn't exist yet, but it will soon™! (You can use `useEffect` to run code at the start of a component rendering.) Here is an example of a JSON response you would get. While the GET /api/donations/:donation_id still doesn't exist yet, you can just hardcode this JSON object in your code instead of getting something like it by making a request to the backend.

```json
{
    "pickup": {
        "pickupTime": "2021-02-14T18:02:55.541Z",
        "dropoffTime": "2021-02-14T18:02:55.541Z",
        "volunteer": {
            "name": "Joe Smith"
        }
    },
    "descriptionImages": [
        "https://umifeedsimageupload.blob.core.windows.net/image-container/bog1.jpeg"
    ],
    "foodImages": [
        "https://umifeedsimageupload.blob.core.windows.net/image-container/bog2.jpeg"
    ],
    "_id": "603cf4599480a8fc3d6552bc",
    "donor": "602965cf42f3f670012ce45e",
    "availability": {
        "_id": "603cf4599480a8fc3d6552bd",
        "startTime": "2021-02-14T14:02:55.541Z",
        "endTime": "2021-02-15T23:02:55.541Z"
    },
    "description": "test donation 55",
    "weight": 55,
    "createdAt": "2021-03-01T14:04:09.907Z",
    "updatedAt": "2021-03-01T14:04:09.907Z",
    "__v": 0
}
```

Soon, we will edit the Donation model so that it lists each individual food, but that will not be done yet. For now, we will use the current Donation model. The page should display the following information:

- start time
- end time
- description
- images
- weight
- pickup information (including volunteer name, pickup time, and dropoff time)

There should be a button to edit the donation, which can take you to the edit donation page (which will be done in another task).

Bonus: At the bottom of the page, display the donor's information.

![image.png](https://images.zenhubusercontent.com/5d8168cc4def500001d12712/2425e61a-29f0-49bc-aa64-e88db6c99503)

**Comment by mariashapiro** [comment]
Endpoint added in #74 so that makes this a tiny bit easier
