### ISSUE TITLE
JWT decoding doesn't actually get email

### ISSUE THREAD

**Issue by XenonMolecule** [GTBitsOfGood/umi-feeds-app#48]
![Screenshot 2021-03-19 at 6 00 03 AM](https://user-images.githubusercontent.com/14205166/111763378-76789880-8878-11eb-99f0-b3455fc09b23.jpeg)
I'm not sure if this is just because I used google SSO, but my email isn't "Michael Ryan" haha.  I noticed this because I was trying to pull the email to pair with the notification token to send to the backend.  It looks like the email is actually getting the value from the name field from the jwt.

**Comment by ML-Chen** [comment]
If this is an inherent limitation with how SSO works with Auth0, then it's okay.
