### ISSUE TITLE
User Profile Screen

### ISSUE THREAD

**Issue by izou3** [GTBitsOfGood/umi-feeds-app#86]
### Problem Description 
Currently there is not any sort of profile screen for the user. Your goal is to change that! 

### Task at Hand
Your mission is to create the user profile screen that will be linked from the user Home Screen. You can view the design in more detail [here](https://www.figma.com/file/p70bLCwileiHQoITFpLpLM/Umi-Feeds-%2F-Fall21?node-id=203%3A940) or view below for your convenience

![umi-feeds-ProfileScreen](https://user-images.githubusercontent.com/55326650/132775758-6433ec02-708c-468d-b82c-92b2c6970ad3.JPG)
 
#### Notes
* Work out of the `/screens/UserProfile/index.tsx` to create the styling for the page 
* You'll need to create a stack for the navigation that includes both the home screen component and an edit form component as indicated by the edit buttons in the mockup
* Since there are currently no link to the screen, simply just import the stack you just created to the main navigation display when you first login at `/navigation/MainNavBar/index.tsx` and replace one of the components currently being linked by the nav bar with your profile component stack. 
* As for obtaining the user data, create a fake user data in the initial User Redux state by filling in the necessary fields, including an array of some addresses and then in your component simply just pull from that state to get the user data. 
* As for the edit buttons next to the business and personal identifications, make sure they're rendered appropriately and for now when they're clicked, just render same component (should be in the UserProfile navigation stack) that just returns the following
```typescript
import * as React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function ProfileScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>User Profile</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  link: {
    marginTop: 15,
    paddingVertical: 15,
  },
  linkText: {
    fontSize: 14,
    color: '#2e78b7',
  },
});
```

### When you're done this is what the app should look like/do:
At the home page, when user clicks on `Me` tab in the navigation bar, they should be taken to a profile page that will return their information. 

### Hints 
* Sorry! Just follow what I wrote in the notes and you'll be good to go! 
### Resources 
* https://reactnative.dev/docs/style

**Comment by phultquist** [comment]
Forgot to comment on commits: 
ec51ddf03b380c32ce5a719bffad9f4253248546
8e19ae0acc9f26a2866e006afc3170186fdadc45
21cfa7f41d09de49f595232a44d212ffc5d7c375
c00514344c6865dbaccc2c736253102e96f5d86b
